In [ ]:
import numpy as np 

In [3]:
# List
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [4]:
np_array = np.array([1,2,3,4,5])
print(np_array)
print(type(np_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# 1D concept
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [7]:
# 2D concept
b = np.array([(1,2,3,4,5), (6,7,8,9,10)])
print(b)
b.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

In [8]:
# create a numpy array of Zeros
c = np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
# create a numpy array of ones
d = np.ones((3,4))
print(d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
# Array of particular value 
e = np.full((3,4),6)
print(e)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [11]:
# Create an array of identity matrix
f = np.eye(4)
print(f)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
# Create an array of random values

g = np.random.random((3,4))
print(g)

[[0.34164352 0.97957865 0.15878344 0.83241722]
 [0.97629641 0.06964447 0.24217007 0.97438929]
 [0.66558412 0.75162322 0.71338916 0.25918308]]


In [ ]:
 # Create an array of random values within a specific range
h = np.random.randint(10, 100, (3,4))
print(h)

[[62 59 49 39]
 [22 74 94 93]
 [13 17 29 45]]


: 

In [18]:
# Array of evenly spaced values  
i = np.linspace(0, 20, 5)
print(i)

[ 0.  5. 10. 15. 20.]


In [19]:
j = np.arange(10, 30, 5)
print(j)

[10 15 20 25]


In [21]:
# Convert a list into numpy array
list2 = [10,20,30,40]
np_array = np.asarray(list2)
print(np_array) 
type(np_array)

[10 20 30 40]


numpy.ndarray

In [22]:
# Analysis a numpy array
k = np.random.randint(10,90,(5,5))
print(k)

[[18 16 38 83 17]
 [48 41 10 82 13]
 [64 11 59 87 31]
 [44 19 28 52 87]
 [10 40 22 82 87]]


In [23]:
print(k.shape)
print(k.ndim)
print(k.size)
print(k.dtype)

(5, 5)
2
25
int32


In [24]:
# Mathematical operation an np array
list2 = [1,2,3,4,5]
list3 = [6,7,8,9,10] 
print(list2 + list3)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [25]:
l = np.random.randint(0,10,(3,3))
m = np.random.randint(10,20,(3,3))
print(l)
print(m)

[[1 4 4]
 [5 4 9]
 [7 3 8]]
[[19 10 12]
 [10 10 16]
 [18 17 18]]


In [26]:
print(l+m)
print(l-m)
print(l*m)
print(l/m)

[[20 14 16]
 [15 14 25]
 [25 20 26]]
[[-18  -6  -8]
 [ -5  -6  -7]
 [-11 -14 -10]]
[[ 19  40  48]
 [ 50  40 144]
 [126  51 144]]
[[0.05263158 0.4        0.33333333]
 [0.5        0.4        0.5625    ]
 [0.38888889 0.17647059 0.44444444]]


In [28]:
#Array Manipulation 
array = np.random.randint(0,10,(2,3))
print(array)

[[0 2 5]
 [9 1 9]]


In [30]:
# Transpose

trans = np.transpose(array)
print(trans)
print(trans.shape)

[[0 9]
 [2 1]
 [5 9]]
(3, 2)
